site_name: 'eData: Documentación'

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
theme:
  name: material
  language: es
  custom_dir: overrides
  include_search_page: false
  search_index_only: true
  font:
    text: Segoe UI
  palette:
    scheme: slate
    primary: lime
    accent: deep orange
  features:
     - navigation.tabs
     - navigation.instant

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - meta # page-specific context
  - pymdownx.highlight:  # better code, instead of CodeHilite
      linenums_style: table
  - pymdownx.inlinehilite # like codehilite but inline
  - pymdownx.superfences
  - toc:
      permalink:         true # inserts an anchor
  - footnotes
  - sane_lists # better ul and ol
  - nl2br # newline hard break
  - pymdownx.betterem:   # better italic and bold
      smart_enable:      asterisk
  - pymdownx.details # details and summary; work with admonition
  - pymdownx.emoji:
      emoji_index:       !!python/name:pymdownx.emoji.twemoji
      emoji_generator:   !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink # auto links
  - pymdownx.tasklist:   # better tasks lists
      custom_checkbox:   true
  - pymdownx.tabbed # auto tabs
  - attr_list



extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/edata-la/

#Page tree
nav:
    - Inicio: index.md
    - Productos:
        - products/ping.md
        - products/ebinlookup.md
    - Setup:
        - Changing the colors: setup/changing-the-colors.md
        - Changing the fonts: setup/changing-the-fonts.md
        - Changing the language: setup/changing-the-language.md
        - Changing the logo and icons: setup/changing-the-logo-and-icons.md
        - Setting up navigation: setup/setting-up-navigation.md
        - Setting up site search: setup/setting-up-site-search.md
        - Setting up site analytics: setup/setting-up-site-analytics.md
        - Setting up the header: setup/setting-up-the-header.md
        - Adding social links: setup/adding-social-links.md
        - Adding a git repository: setup/adding-a-git-repository.md
        - Adding a comment system: setup/adding-a-comment-system.md
        #- Adding a landing page: setup/adding-a-landing-page.md
    - Reference:
        - Abbreviations: reference/abbreviations.md
        - Admonitions: reference/admonitions.md
        - Buttons: reference/buttons.md
        - Code blocks: reference/code-blocks.md
        - Content tabs: reference/content-tabs.md
        - Data tables: reference/data-tables.md
        - Footnotes: reference/footnotes.md
        - Formatting: reference/formatting.md
        - Icons + Emojis: reference/icons-emojis.md
        - Images: reference/images.md
        - Lists: reference/lists.md
        - MathJax: reference/mathjax.md
        - Meta tags: reference/meta-tags.md
        - Variables: reference/variables.md
    - Changelog:
        - Release notes: changelog.md
        - Upgrading: upgrading.md
        - Deprecations: deprecations.md